[package]
name = "ribbit-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.23.0"
heck = "0.5"
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = { version = "2.0.114", default-features = false, features = ["derive", "parsing", "proc-macro"] }
